# Generated by Django 4.1.7 on 2023-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('town_city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('date', models.DateTimeField(verbose_name='date of event')),
                ('attendee_count', models.IntegerField(default=0)),
                ('organiser', models.CharField(max_length=100)),
            ],
        ),
    ]
