# Generated by Django 4.1 on 2023-03-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_building_name_address_buildingname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.AddField(
            model_name="event",
            name="address1",
            field=models.TextField(default="N/A", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="address2",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="postcode",
            field=models.TextField(default="BA2 7AY", max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
