# Generated by Django 4.1 on 2023-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_address_event_address1_event_address2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("FoodTasting", "FoodTasting"),
                    ("Movies", "Movies"),
                    ("Club", "Club"),
                    ("Sports", "Sports"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
