# Generated by Django 4.1 on 2023-03-14 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("1d6ccd1a-c6a2-4de4-99c9-846aaad5ef82"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
