# Generated by Django 4.1 on 2023-03-14 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("a3fdbddf-8006-4fb4-96c5-c427130d425a"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
