# Generated by Django 4.1 on 2023-03-14 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_file_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("a58de98c-190b-42bc-a58b-e91d62c9f675"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
