# Generated by Django 4.1 on 2023-03-14 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("768ea839-89da-4e33-91d4-dd4cfbc8ce88"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
