# Generated by Django 4.1 on 2023-03-15 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("20865804-e79d-4784-88c7-3f757846c43f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
