# Generated by Django 4.1 on 2023-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_sociallinks_facebook_alter_sociallinks_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuser",
            name="socialLinks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.sociallinks"
            ),
        ),
    ]
