# Generated by Django 4.1 on 2023-02-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_ccuser_sociallinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuser",
            name="socialLinks",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.sociallinks",
            ),
        ),
    ]
