# Generated by Django 4.1 on 2023-02-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_ccuser_sociallinks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ccuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="ccuser",
            name="followedUsers",
        ),
        migrations.RemoveField(
            model_name="ccuser",
            name="profilePic",
        ),
        migrations.RemoveField(
            model_name="ccuser",
            name="socialLinks",
        ),
        migrations.RemoveField(
            model_name="ccuser",
            name="userType",
        ),
        migrations.CreateModel(
            name="CCUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=20)),
                ("dateJoined", models.DateTimeField(auto_now_add=True)),
                (
                    "userType",
                    models.TextField(
                        choices=[
                            ("S_ADMIN", "SiteAdmin"),
                            ("ORGNAISER", "ORGNAISER"),
                            ("USER", "USER"),
                        ],
                        default="USER",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="")),
                (
                    "followedUsers",
                    models.ManyToManyField(
                        related_name="followers", to="user.ccuserprofile"
                    ),
                ),
                (
                    "socialLinks",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sociallinks",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
