# Generated by Django 4.1 on 2023-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_ccuserprofile_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuserprofile",
            name="facebook",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="ccuserprofile",
            name="followedUsers",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="user.ccuserprofile"
            ),
        ),
        migrations.AlterField(
            model_name="ccuserprofile",
            name="instagram",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="ccuserprofile",
            name="twitter",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="ccuserprofile",
            name="website",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
