# Generated by Django 4.1 on 2023-03-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_ccuserprofile_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuserprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="ccuserprofile",
            name="userType",
            field=models.TextField(
                choices=[
                    ("S_ADMIN", "SiteAdmin"),
                    ("ORGANISER", "ORGANISER"),
                    ("USER", "USER"),
                ],
                default="USER",
            ),
        ),
    ]
