# Generated by Django 4.1 on 2023-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_ccuserprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuserprofile",
            name="userType",
            field=models.TextField(
                choices=[("ORGANISER", "ORGANISER"), ("USER", "USER")], default="USER"
            ),
        ),
    ]
