# Generated by Django 4.1 on 2023-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_ccuserprofile_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccuserprofile",
            name="avatar",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
