# Generated by Django 4.1.7 on 2023-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_ccuserprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccuserprofile',
            name='userType',
            field=models.TextField(choices=[('ORGANISER', 'ORGANISER'), ('USER', 'USER')], default='ORGANISER'),
        ),
    ]
